arii_Config_index:
    pattern:  /
    defaults: { _controller: AriiConfigBundle:Default:index }

json_Config_ribbon:
    pattern:  /ribbon.json
    defaults: { _controller: AriiConfigBundle:Default:ribbon }

arii_Config_readme:
    pattern:  /readme
    defaults: { _controller: AriiConfigBundle:Default:readme }

json_Config_tree_menu:
    pattern:  /tree_menu.json
    defaults: { _controller: AriiConfigBundle:Default:menu }

arii_Config_phpinfo:
    pattern:  /phpinfo.php
    defaults: { _controller: AriiConfigBundle:Default:phpinfo }

arii_Config_save_db:
    pattern:  /save_db.php
    defaults: { _controller: AriiConfigBundle:Default:save_db }

#============================================================
# Enterprises
#------------------------------------------------------------
arii_Config_enterprises:
    pattern:  /enterprises
    defaults: { _controller: AriiConfigBundle:Enterprises:index}

xml_Config_enterprises_toolbar:
    pattern:  /enterprises/toolbar.xml
    defaults: { _controller: AriiConfigBundle:Enterprises:toolbar}

xml_Config_enterprises_grid:
    pattern:  /enterprises/grid.xml
    defaults: { _controller: AriiConfigBundle:Enterprises:grid}

xml_Config_enterprises_menu:
    pattern:  /enterprises/menu.xml
    defaults: { _controller: AriiConfigBundle:Enterprises:menu}

#============================================================
# Enterprise
#------------------------------------------------------------
arii_Config_enterprise_new:
    pattern:  /enterprise/new
    defaults: { _controller: AriiConfigBundle:Enterprise:new}

xml_Config_enterprise_toolbar:
    pattern:  /enterprise/toolbar.xml
    defaults: { _controller: AriiConfigBundle:Enterprise:toolbar}

xml_Config_enterprise_form:
    pattern:  /enterprise/form.xml
    defaults: { _controller: AriiConfigBundle:Enterprise:form }

xml_Config_enterprise_delete:
    pattern:  /enterprise/delete
    defaults: { _controller: AriiConfigBundle:Enterprise:delete }

xml_Config_enterprise_save:
    pattern:  /enterprise/save
    defaults: { _controller: AriiConfigBundle:Enterprise:save }

arii_Config_enterprise_create:
    pattern:  /enterprise/create
    defaults: { _controller: AriiConfigBundle:Enterprise:create }

#============================================================
# Web server
#------------------------------------------------------------
arii_Config_web_server:
    pattern:  /webserver
    defaults: { _controller: AriiConfigBundle:Webserver:index }

